adapter: qlora
base_model: unsloth/llama-3-8b-Instruct
bf16: auto
datasets:
- path: Yukang/LongAlpaca-12k
  type: alpaca
flash_attention: false
fsdp:
- full_shard
- auto_wrap
fsdp_config:
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: true
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 0.0002
load_in_4bit: true
load_in_8bit: false
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_r: 32
lora_target_linear: true
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch
output_dir: ./models/llama70B-LongAlpaca
pad_to_sequence_len: true
sequence_length: 1024
special_tokens:
  pad_token: <|end_of_text|>
tf32: false
