import os
from litellm import completion


DEFAULT_MODEL_NAME=os.getenv("PRICER_PREPROCESSOR_MODEL", "ollama/llama3.2")
DEFAULT_REASONING_EFFORT="low" if "gpt-oss" in DEFAULT_MODEL_NAME else None

SYSTEM_PROMPT="""Create a concise description of a product. Respond only in this format. Do not include part numbers.
Title: Rewritten short precise title
Category: eg Electronics
Brand: Brand name
Description: 1 sentence description
Details: 1 sentence on features"""

class Preprocessor:
    """
    Preprocesses raw product text using an LLM to generate a concise,
    structured product description.

    The preprocessor sends the input text along with a system prompt to
    the configured language model and tracks token usage and estimated
    processing cost.

    Attributes:
        total_input_tokens (int): Total number of input/prompt tokens used.
        total_output_tokens (int): Total number of output/completion tokens used.
        total_cost (float): Estimated total cost of all model requests.
        model_name (str): Name of the language model used for preprocessing.
        reasoning_effect (str | None): Reasoning effort level passed to the model.
        base_url (str | None): Base URL of the model API.
    """
    def __init__(
        self,
        model_name=DEFAULT_MODEL_NAME,
        reasoning_effect=DEFAULT_REASONING_EFFORT,
        base_url=None
    ):
        """
        Initialize a Preprocessor instance.

        Args:
            model_name (str): Name of the LLM to use. Defaults to the value
                of the PRICER_PREPROCESSOR_MODEL environment variable or
                "ollama/llama3.2".
            reasoning_effect (str | None): Reasoning effort to request from
                the model. Defaults to "low" for gpt-oss models and None
                otherwise.
            base_url (str | None): Base URL for the model API. If an Ollama
                model is used and no URL is provided, defaults to the local
                Ollama server at http://localhost:11434.
        """
        self.total_input_tokens = 0
        self.total_output_tokens = 0
        self.total_cost = 0
        self.model_name = model_name
        self.reasoning_effect = reasoning_effect
        self.base_url = base_url

        if ("ollama" in model_name) and (not base_url):
            self.base_url = "http://localhost:11434"
    
    def messages_for(self, text:str) -> list[dict]:
        """
        Build the chat messages sent to the language model.

        Args:
            text (str): Raw product text to be preprocessed.

        Returns:
            list[dict]: A list containing the system prompt and the user's
                product text in the format expected by LiteLLM.
        """
        return [{"role": "system", "content": SYSTEM_PROMPT}, {"role": "user", "content": text}]
    
    def preprocess(self, text:str) -> str:
        """
        Preprocess product text using the configured language model.

        The method sends the product text to the LLM, updates cumulative
        input/output token counts and estimated cost, and returns the
        model-generated structured product description.

        Args:
            text (str): Raw product text to preprocess.

        Returns:
            str: A concise, structured product description generated by
                the language model.
        """
        messages = self.messages_for(text=text)
        response = completion(
            messages=messages,
            model=self.model_name,
            reasoning_effort=self.reasoning_effect,
            api_base=self.base_url,
        )
        self.total_input_tokens += response.usage.prompt_tokens
        self.total_output_tokens += response.usage.completion_tokens
        self.total_cost += response._hidden_params["response_cost"]
        return response.choices[0].message.content
